services:
  app:
    build: .
    image: warehouse-management-system-image-8090
    container_name: warehouse-management-system-8090
    restart: always
    network_mode: bridge
    ports:
      - "8090:8090"
    environment:
      - PORT=8090
      - DB_HOST=localhost
      - DB_NAME=warehouse
      - DB_USERNAME=root
      - DB_PASSWORD=root1997
