spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  datasource:
    url: jdbc:mysql://${DB_HOST:warehouse-management-system:3306}/${DB_NAME:warehouse}  # Internal MySQL port
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root1997}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: false
        format_sql: true
        generate_statistics: false

  liquibase:
    change-log: classpath:db/changelog/master-changelog.yaml
    parameters:
      searchPath: classpath:/, db/changelog/
server:
  port: 8090
